config/routes.rb
MDS::Application.routes.draw do
  get "boxoffice/partial"
  get "lists/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations",
    :passwords => "passwords", :invitations => "invitations"}

  devise_scope :user do
    get "/users/:username/lists" => "lists#index", :as => :user_lists
    post "/users/:username/lists" => "lists#create"
    get "/users/:username/lists/new" => "lists#new", :as => :new_user_list
    get "/users/:username/lists/:id/edit" => "lists#edit", :as => :edit_user_list
    get "/users/:username/lists/:id" => "lists#show", :as => :user_list
    patch "/users/:username/lists/:id" => "lists#update"
    put "/users/:username/lists/:id" => "lists#update"
    delete "/users/:username/lists/:id" => "lists#destroy"
    
    delete "/users/:username/lists/:id/:movie_id" => "lists#remove_movie", :as => :remove_user_list_movie
    get "/users/:username/lists/:id/add" => "lists#add_movies", :as => :user_list_list_movie_pairs
    post "/users/:username/lists/:id/add" => "lists#submit_movies"

    get "/users/:username/invitations" => "invitations#index", :as => :user_invitations

    get "/users/:username/reviews" => "reviews#index", :as => :user_reviews
    post "/users/:username/reviews" => "reviews#create"
    get "/users/:username/reviews/new/:id" => "reviews#new", :as => :new_user_review
    get "/users/:username/reviews/:id/edit" => "reviews#edit", :as => :edit_user_review
    get "/users/:username/reviews/:id" => "reviews#show", :as => :user_review
    patch "/users/:username/reviews/:id" => "reviews#update"
    put "/users/:username/reviews/:id" => "reviews#update"
    delete "/users/:username/reviews/:id" => "reviews#destroy"
  end

  resources :movies

  get 'search' => 'searches#search'
  get "in_place_search" => "searches#in_place_search", :as => :in_place_search
  
  root 'welcome#home'

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :list_movie_pairs
	has_many :movies, :through => :list_movie_pairs

	validates_length_of :name, maximum: 50
	validates_length_of :description, maximum: 500
	validates_presence_of :name, :user_id
	validates_inclusion_of :private, in: [true, false]
	validate :validate_movies_count

	# accepts_nested_attributes_for :list_movie_pairs, :allow_destroy => true
	# accepts_nested_attributes_for :movies, :allow_destroy => true

private
	def validate_movies_count
		errors.add(:list_movie_pairs, "too many") if list_movie_pairs.size > 50
	end
end

app/controllers/lists_controller.rb
require 'open-uri'
require 'json'

class ListsController < ApplicationController	
  before_action :authenticate_user!

  helper_method :list
  helper_method :user_lists

  def index
    @user = User.find_by_username(params[:username])
    @lists = @user.lists.page(params[:page]).per(10).order('created_at DESC')
    @public_lists_count = @lists.where(private: false).count
  end

  def new
    @list = current_user.lists.new
  end

  def create
  	@list = current_user.lists.new(list_params)

  	if @list.save
      redirect_to user_list_list_movie_pairs_path(current_user.username, list)
   	else
	    render :new
  	end
  end

  def edit
  end

  def update
  	list.update(list_params)

    if @list.save
      redirect_to user_lists_path(current_user.username)
    else
      render :edit
    end
  end

  def show
    @exists = !(List.where(id: params[:id]).empty?)

    if @exists
      @user = User.find_by_username(params[:username])
      @movies = list.movies.page(params[:page]).per(20)
    end
  end

  def destroy
    deleted_list = current_user.lists.find(params[:id])
    deleted_list.destroy
    redirect_to user_lists_path(current_user.username)
  end

  def remove_movie
    movie = Movie.find(params[:movie_id])
    if movie
      list.movies.delete(movie)
    end
      redirect_to user_list_path(current_user.username, params[:id])
  end

  def add_movies
    @pair = list.list_movie_pairs.new
  end

  def submit_movies
    @list = current_user.lists.find(params[:id])
    @pair = @list.list_movie_pairs.new(pair_params)
    
    remote_id = @pair.movie_id
    unless Movie.find_by_rotten_tomatoes_id(remote_id)
        Movie.create(title: movie_title(remote_id), year: movie_year(remote_id), \
          rotten_tomatoes_id: remote_id, thumbnail_poster_link: movie_thumbnail(remote_id), \
          detailed_poster_link: movie_poster(remote_id))
    end

    @pair.movie_id = Movie.find_by_rotten_tomatoes_id(remote_id).id

    if @pair.save      
      redirect_to user_list_path(current_user.username, @list)
    else
      render :add_movies
    end
  end

private

  def movie_request(id)
    apilink = 'http://api.rottentomatoes.com/api/public/v1.0/'
    apikey = 'haak3yvy8dsw4gfxu8vprvnv'
    @link = apilink + 'movies/' + id.to_s + '.json?apikey=' + apikey
    search_string = URI.parse(@link).read
  end

  def movie_query(json_string)
    parsed_json = JSON.parse(json_string)
  end

  def movie_title(remote_id)
    search_results = movie_request(remote_id)
    @movie = movie_query(search_results)
    @movie['title']
  end

  def movie_year(remote_id)
    # search_results = movie_request(remote_id)
    # movie = movie_query(search_results)
    @movie['year']
  end

  def movie_thumbnail(remote_id)
    @movie['posters']['thumbnail']
  end

  def movie_poster(remote_id)
    @movie['posters']['detailed']
  end

  def user_lists
    user_lists = User.find_by_username(params[:username]).lists
  end

  def list
    @list ||= user_lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :description, :private)#,
      # list_movie_pairs_attributes: [:id, :list_id, :movie_id, :_destroy],
      # movies_attributes: [:id, :title, :_destroy])
  end

  def pair_params
    params.require(:list_movie_pair).permit(:list_id, :movie_id)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/add_movies.html.erb
<div class="col-md-5">

<%= link_to 'My lists', user_lists_path(current_user.username), :class => 'btn btn-primary', :id => 'mylist' %>


 <%= simple_form_for [current_user, list, @pair] do |f| %>

  <%= f.input :movie_id, input_html: { class: "input_field" } %>

  <%= f.button :submit, "Submit", class: 'btn btn-primary' %> 
  <%= link_to "Cancel", user_lists_path(current_user.username), class: 'btn btn-default' %>
<% end %>
</div>

app/views/lists/edit.html.erb
<div class="col-md-3">
  <h2> Edit list </h2>
<%= simple_form_for [current_user, list], :url => { :action => 'update'} do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :private, label: "Visibility",
  as: :radio_buttons, 
  collection: [["private", list.private], ["public", !list.private]],
  checked: true %>
  
  <%= f.button :submit, :class => 'btn btn-primary' %>  
  <%= link_to "Cancel", user_lists_path(current_user.username), :class => 'btn btn-default' %>
<% end %>
</div>

app/views/lists/index.html.erb
<%= bootstrap_flash %>

<h1>
  <% if @user == current_user %>
    <h2>My Lists </h2>
  <% else %>
    <h2> <%= @user.username %>'s Lists </h2>
  <% end %>
</h1>

<% if @lists.length == 0 %>
  <% if @user == current_user %>
    <p>You have no lists. <%= link_to 'Create one', new_user_list_path(current_user.username)%> now!</p>
  <% else %>
    <p>This user has no public lists.</p>
  <% end %>
<% else %>

  <% if @user != current_user && @public_lists_count == 0 %>
      <p>This user has no public lists.</p>
  <% else %>
  <%= link_to 'New list', new_user_list_path(current_user.username), class: "btn btn-primary"%>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <% if @user == current_user %>
            <th>Visibility</th>
          <% end %>
          <th> Options </th>
        </tr>
      </thead>

      <% @lists.each do |list| %>
        <% unless @user != current_user && list.private == true %>
          <tr>
            <td><%= list.name %></td>
            <td><%= "#{list.description[0..35]}..." %></td>
            <% if @user == current_user %>
              <td>
                <% if list.private == true %>
                  Private
                <% else %>
                  Public
                <% end %>
              </td>
            <% end %>
            <td><%= link_to 'Show', user_list_path(@user.username, list), :class => 'btn btn-primary' %>
            <% if @user == current_user %>
              <%= link_to 'Edit', edit_user_list_path(current_user.username, list), :method => :get, :class => 'btn btn-primary' %>
              <%= link_to 'Delete', 
              user_list_path(current_user.username, list), :method => :delete,
                :data => { :confirm => "Press Ok to Delete the List \"#{list.name}\"."},
                :class => 'btn btn-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </table>
    <%= paginate @lists, :theme => 'twitter-bootstrap-3'%>
  <% end %>
 
<% end %>

app/views/lists/new.html.erb
  <%= bootstrap_flash%>

  <h2> Add details about your list </h2>

  <div class="col-md-3">
    <%= simple_form_for [current_user, @list], :html => { :class => 'form-horizontal' } do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :private, label: "Visibility",
          as: :radio_buttons, 
          collection: [["private", true], ["public", false]],
          checked: true %>
      </div>
      <div class="form-actions form-button">
        <%= f.button :submit, "Add movies to your list", :class => 'btn btn-primary' %> 
        <%= link_to "Cancel", user_lists_path(current_user.username), :class => 'btn btn-default' %>
      </div>
    <% end %>
  </div>

app/views/lists/show.html.erb
<% if @exists == false || (@user != current_user && list.private == true) %>
	<h1>Sorry!</h1>
	<p>The page does not exist</p>
<% else %>

	<%= link_to @user == current_user ? "My lists" : "All lists", user_lists_path(@user.username), :class => 'btn btn-primary' %>

	<h1><%= list.name %></h1>

	<p><%= list.description %></p>
	<% if @user == current_user %>
		<% if list.private == true %>
			<p>This list is <b>private</b>.<p>
		<% else %>
			<p>This list is <b>public</b>.<p>
		<% end %>

		<%= link_to "Add movie", user_list_list_movie_pairs_path(current_user.username, list), class: "btn btn-primary" %>
	<% end %>

	<table class="table table-striped">
		<thead>
		<tr> <th> Poster </th>
			<th> Title </th>
			<th> Options </th></tr>
		</thead>
		<% @movies.each do |movie| %>
			<tr>
				<td><%= link_to image_tag(movie.thumbnail_poster_link, size: '61x91'), movie_path(:movie_id => movie.rotten_tomatoes_id, :id => 'show') %></td>
				<td><%= link_to "#{movie.title} (#{movie.year})", movie_path(:movie_id => movie.rotten_tomatoes_id, :id => 'show') %></td>
				<% if @user == current_user %>
					<td><%= link_to "Remove", 

					    remove_user_list_movie_path(movie_id: movie.id), :method => :delete,
					    :data => { :confirm => "Remove?"},
					    :class => "btn btn-danger" %></td>
				<% end %>
			</tr>
		<% end %>
	</table>

	<%= paginate @movies, theme: "twitter-bootstrap-3" %>
<% end %>