config/routes.rb
MDS::Application.routes.draw do
  get "boxoffice/partial"
  get "lists/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations",
    :passwords => "passwords", :invitations => "invitations"}

  devise_scope :user do
    get "/users/:username/lists" => "lists#index", :as => :user_lists
    post "/users/:username/lists" => "lists#create"
    get "/users/:username/lists/new" => "lists#new", :as => :new_user_list
    get "/users/:username/lists/:id/edit" => "lists#edit", :as => :edit_user_list
    get "/users/:username/lists/:id" => "lists#show", :as => :user_list
    patch "/users/:username/lists/:id" => "lists#update"
    put "/users/:username/lists/:id" => "lists#update"
    delete "/users/:username/lists/:id" => "lists#destroy"
    
    delete "/users/:username/lists/:id/:movie_id" => "lists#remove_movie", :as => :remove_user_list_movie
    get "/users/:username/lists/:id/add" => "lists#add_movies", :as => :user_list_list_movie_pairs
    post "/users/:username/lists/:id/add" => "lists#submit_movies"

    get "/users/:username/invitations" => "invitations#index", :as => :user_invitations

    get "/users/:username/reviews" => "reviews#index", :as => :user_reviews
    post "/users/:username/reviews" => "reviews#create"
    get "/users/:username/reviews/new/:id" => "reviews#new", :as => :new_user_review
    get "/users/:username/reviews/:id/edit" => "reviews#edit", :as => :edit_user_review
    get "/users/:username/reviews/:id" => "reviews#show", :as => :user_review
    patch "/users/:username/reviews/:id" => "reviews#update"
    put "/users/:username/reviews/:id" => "reviews#update"
    delete "/users/:username/reviews/:id" => "reviews#destroy"
  end

  resources :movies

  get 'search' => 'searches#search'
  get "in_place_search" => "searches#in_place_search", :as => :in_place_search
  
  root 'welcome#home'

end

app/controllers/movies_controller.rb
require 'open-uri'
require 'json'
require 'nokogiri'

class MoviesController < ApplicationController

  helper_method :rotten_tomatoes_movie_id
  helper_method :movie_title
  helper_method :thumbnail_poster
  helper_method :detailed_poster

  def show
	json_string = movie_request(params[:movie_id])
	@movie = movie_query(json_string)

	@youtube_trailer_id = trailer_request(@movie['title'], @movie['year'].to_s)

	# add movie to database if it's not already
	if Movie.exists?(:rotten_tomatoes_id => params[:movie_id]) == false
	  movie_title = @movie['title']

	  new_movie = Movie.new(:rotten_tomatoes_id => params[:movie_id], :title => movie_title, :year => movie_year, :thumbnail_poster_link => thumbnail_poster, :detailed_poster_link => detailed_poster)

	  new_movie.save
	end

	@existent_movie = Movie.where(:rotten_tomatoes_id => params[:movie_id]).first

	@reviews = Review.where(:movie_id => @existent_movie.id)
	@rating = 0
	if @reviews.empty? == false
		@reviews.each do |review|
			@rating = @rating + review.rating
		end
		@rating = @rating / @reviews.length
	else
		@rating = "unrated"
	end

	if user_signed_in?
	  @current_user_review = @reviews.find_by_user_id(current_user.id)
	else
	  @current_user_review = nil;
	end

	@public_reviews_count = 0
	@reviews.each do |review|
	  if review.private == false and (user_signed_in? == false or review.user_id != current_user.id)
	  	@public_reviews_count = @public_reviews_count + 1
	  end
	end
  end

  private

  # return the video id on youtube
  # => It use YouTube api and suppose that
  # => first result is actually the best result
  # TODO => Refactor this code when we have time
  def trailer_request( title , year )
    # create the query string for movie
    query = title.gsub(' ', '+') + '+' + year;
	# the basic link for the YouTube API
	youtube_api_link = 'https://gdata.youtube.com/feeds/api/videos' 
  	# create the link with all the above informations
  	youtube_link = youtube_api_link + '?q=' + query;
  	# takes and parse the XML using a HTTP request on the API
	doc = Nokogiri::XML(open(youtube_link))
	# get the video embeded link on youtube
	doc = doc.xpath('//xmlns:feed/xmlns:entry/xmlns:id')[0].to_s;
	doc.gsub('<id>http://gdata.youtube.com/feeds/api/videos/', '').gsub('</id>', '')
  end

  # return the jSon string returned by the API
  # for a particular movie specified by 'id'
  def movie_request( id )
	# the basic link for the API (without any query specified properties)
	apilink = 'http://api.rottentomatoes.com/api/public/v1.0/'
	# the key for the API
	# TODO: change api key when this is ready
	apikey = 'haak3yvy8dsw4gfxu8vprvnv'
	# create the link with all of the above informations
	@link = apilink + 'movies/' + id.to_s + '.json?apikey=' + apikey
	# takes the jSon string using a HTTP request on the API
	search_string = URI.parse(@link).read
  end

  # return a recursive structure (somthing like a hash of hashes)
  # this structure keep informations about the movies
  def movie_query( json_string )
	# parse the jSon string in a recursive structure
	# return this structure
	parsed_json = JSON.parse(json_string)
  end

  def movie_title
  	@movie['title']
  end

  def rotten_tomatoes_movie_id
  	@movie['id']
  end

  def movie_year
  	@movie['year']
  end

  def thumbnail_poster
		if @movie['posters'] and @movie['posters']['thumbnail']
		  thumbnail = @movie['posters']['thumbnail']
		else
			nil
		end
  end

  def detailed_poster
	if @movie['posters'] and @movie['posters']['detailed']
	  thumbnail = @movie['posters']['detailed']
	else
	  nil
	end
  end

  def database_movie_id

  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/show.html.erb
<!-- Aici sunt toate informatiile pe care le poti obtine de la api-->

<table class="header-informations">
  <tr>
    <td class="poster"> <%= image_tag(@movie['posters']['detailed']) %> </td>
    <td class="important-informations">
	    <h1><%= @movie['title'] %></h1>
	    <h2><%= @movie['year'] %></h2>	
      <h4>Average rating: <%= @rating %></h4>
    </td>
  </tr>
</table>	

<table>
  <tr>
	<td><strong>Genres</td>
	<td><br><% @movie['genres'].each do |genre| %>
    <li><%= genre %></li>
  <% end %>
</td>
  </tr>
  <tr>
    <td><strong>User Rating</strong><br></td>
    <td><%= @movie['mpaa_rating'] %><br></td>
  </tr>
  <tr>
	 <td><strong>Runtime</strong><br></td>
	 <td><%= @movie['runtime'] %><br></td>
  </tr>
  <tr>
	 <td><strong>Critics' opinion</strong><br></td>
	 <td><%= @movie['critics_consensus'] %><br></td>
  </tr>
  <tr>
	 <td><strong>Release dates</strong><br></td>
	 <td><ul><br><li>Theater = <%= @movie['release_dates']['theater'] %></li>
	 <% if @movie['release_dates']['dvd'] %> <!-- adica daca exista campul 'dvd' (nu este null) --> 
	   <li>DVD = <%= @movie['release_dates']['dvd'] %><br></li> 
	 <% end %>
	 </ul></td>
  </tr>
</table>

<!-- This part is for movie reviews -->
<% if @reviews.length != 0 %>
  <% if user_signed_in? %>
    <% if @current_user_review %>
      <div class="well" >
        <h4>Your Review</h4>
        <p>Rating: <%= @current_user_review.rating %></p>
        <p>Review: <%= @current_user_review.comment %></p>
        <%= link_to 'Edit ' + movie_title + '\'s review', edit_user_review_path(current_user.username, @current_user_review.id), :method => :get , :class => 'btn btn-primary' %>
      </div>
      <% else %>
        <%= link_to 'Review ' + movie_title, new_user_review_path(current_user.username, @existent_movie.id), :method => :get, :class => 'btn btn-primary' %>
    <% end %>
  <% end %>
  <% if @public_reviews_count != 0 %>
    <h2> User Reviews </h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Username</th>
          <th>Rating</th>
          <th>Review</th>
        </tr>
      </thead>
      <% @reviews.each do |review| %>
        <% if user_signed_in? == false or (user_signed_in? and review.user_id != current_user.id) %>
          <% if review.private == false %>
            <tr>
              <td> <%= User.find(review.user_id).username %> </td>
              <td> <%= review.rating %> </td>
              <td> <%= review.comment %> </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </table>
  <% else %>
    <h2> User Reviews </h2>
    <% if user_signed_in? and @current_user_review%>
      <p>There are no more public reviews for <%= movie_title %> !</p>
    <% else %>
      <p>There are no public reviews for <%= movie_title %> !</p>
    <% end %>
  <% end %>
<% else %>
  <% if user_signed_in? %>
     <%= link_to 'Review ' + movie_title, new_user_review_path(current_user.username, @existent_movie.id), :method => :get, :class => 'btn btn-primary' %>
  <% end %>
  <h2> User Reviews </h2>
  <p>No reviews for this movie yet!</p>
  <p></p>
<% end %>

<!-- trailer -->
<!-- TODO => Refactor this code when we have time -->
<h2>Movie Trailer </h2>
<iframe id="player" type="text/html" width="640" height="390" src= <%= "http://www.youtube.com/embed/#{@youtube_trailer_id}" %> frameborder="0"></iframe>

<%
=begin
%>

<table>
   <% @reviews.each_with_index do |movieReview, index| %>
      <tr>
         <td><%= "Review no: #{index} ... " %></td>
      </tr>
      <tr>
         <td><%= movieReview.comment %></td>
      </tr>
   <% end %>
</table>

<%
=end
%>

<!--
Asta e structura normala a json-ului returnat de api-ul nostru pentru un film:
Exemplul in cauza este Noah 

Atentie!!! Nu trebuie sa se presupuna ca orice film 
va avea toate campurile de mai jos. Trebuiesc testate toate campurile asa cum
am dat exemplu mai jos

Pentru detalii despre json va rog cititi: http://www.json.org/
	Este doar o pagina si este foarte friendly explicata

{
   "id":771305170,
   "title":"Noah",
   "year":2014,
   "genres":[
      "Drama",
      "Classics"
   ],
   "mpaa_rating":"PG-13",
   "runtime":139,
   "critics_consensus":"With sweeping visuals grounded by strong performances in service of a timeless tale told on a human scale, Darren Aronofsky's Noah brings the Bible epic into the 21st century.",
   "release_dates":{
      "theater":"2014-03-28"
   },
   "ratings":{
      "critics_rating":"Certified Fresh",
      "critics_score":76,
      "audience_rating":"Spilled",
      "audience_score":47
   },
   "synopsis":"Russell Crowe stars as Noah in the film inspired by the epic story of courage, sacrifice and hope. Directed by visionary filmmaker Darren Aronofsky (c) Paramount",
   "posters":{
      "thumbnail":"http://content9.flixster.com/movie/11/17/69/11176923_mob.png",
      "profile":"http://content9.flixster.com/movie/11/17/69/11176923_pro.png",
      "detailed":"http://content9.flixster.com/movie/11/17/69/11176923_det.png",
      "original":"http://content9.flixster.com/movie/11/17/69/11176923_ori.png"
   },
   "abridged_cast":[
      {
         "name":"Russell Crowe",
         "id":"162652569",
         "characters":[
            "Noah"
         ]
      },
      {
         "name":"Jennifer Connelly",
         "id":"162652853",
         "characters":[
            "Naameh"
         ]
      },
      {
         "name":"Ray Winstone",
         "id":"162693523",
         "characters":[
            "Tubal Cain"
         ]
      },
      {
         "name":"Emma Watson",
         "id":"162655378",
         "characters":[
            "Il-la",
            "Ila"
         ]
      },
      {
         "name":"Anthony Hopkins",
         "id":"162653967",
         "characters":[
            "Methuselah"
         ]
      }
   ],
   "abridged_directors":[
      {
         "name":"Darren Aronofsky"
      }
   ],
   "studio":"Paramount Pictures",
   "alternate_ids":{
      "imdb":"1959490"
   },
   "links":{
      "self":"http://api.rottentomatoes.com/api/public/v1.0/movies/771305170.json",
      "alternate":"http://www.rottentomatoes.com/m/noah_2014/",
      "cast":"http://api.rottentomatoes.com/api/public/v1.0/movies/771305170/cast.json",
      "clips":"http://api.rottentomatoes.com/api/public/v1.0/movies/771305170/clips.json",
      "reviews":"http://api.rottentomatoes.com/api/public/v1.0/movies/771305170/reviews.json",
      "similar":"http://api.rottentomatoes.com/api/public/v1.0/movies/771305170/similar.json"
   }
}
-->