config/routes.rb
MDS::Application.routes.draw do
  get "boxoffice/partial"
  get "lists/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations",
    :passwords => "passwords", :invitations => "invitations"}

  devise_scope :user do
    get "/users/:username/lists" => "lists#index", :as => :user_lists
    post "/users/:username/lists" => "lists#create"
    get "/users/:username/lists/new" => "lists#new", :as => :new_user_list
    get "/users/:username/lists/:id/edit" => "lists#edit", :as => :edit_user_list
    get "/users/:username/lists/:id" => "lists#show", :as => :user_list
    patch "/users/:username/lists/:id" => "lists#update"
    put "/users/:username/lists/:id" => "lists#update"
    delete "/users/:username/lists/:id" => "lists#destroy"
    
    delete "/users/:username/lists/:id/:movie_id" => "lists#remove_movie", :as => :remove_user_list_movie
    get "/users/:username/lists/:id/add" => "lists#add_movies", :as => :user_list_list_movie_pairs
    post "/users/:username/lists/:id/add" => "lists#submit_movies"

    get "/users/:username/invitations" => "invitations#index", :as => :user_invitations

    get "/users/:username/reviews" => "reviews#index", :as => :user_reviews
    post "/users/:username/reviews" => "reviews#create"
    get "/users/:username/reviews/new/:id" => "reviews#new", :as => :new_user_review
    get "/users/:username/reviews/:id/edit" => "reviews#edit", :as => :edit_user_review
    get "/users/:username/reviews/:id" => "reviews#show", :as => :user_review
    patch "/users/:username/reviews/:id" => "reviews#update"
    put "/users/:username/reviews/:id" => "reviews#update"
    delete "/users/:username/reviews/:id" => "reviews#destroy"
  end

  resources :movies

  get 'search' => 'searches#search'
  get "in_place_search" => "searches#in_place_search", :as => :in_place_search
  
  root 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<%= stylesheet_link_tag "welcomehome", media: "all", "data-turbolinks-track" => true %>
<%= bootstrap_flash %>
<br>

<% if user_signed_in? %>
<h3>Welcome, <%= current_user.username %>!</h3><br><br>
 <div class="panel panel-info">
    <div class="panel panel-heading">
     <h4>Your newest lists</h4>
    </div>
  <div class="panel panel-body">
  <% if current_user.lists.any?%>
    
      <ul>
      <% current_user.lists[0..5].each do |list| %>
        <li><span class="glyphicon glyphicon-film"></span>
          <%= link_to list.name, user_list_path(current_user.username, list.id) %></li>
      <% end %>
      </ul>  
  <%else%>
      <h4> You don't have any lists yet! - <%=link_to 'create one', new_user_list_path(current_user.username)%> now</h4>
  <%end%>
  </div>
</div>
  

  <div class="panel panel-info">
    <div class="panel panel-heading">
      <h4>Your latest reviews</h4>
    </div>
    
    <div class="panel panel-body">
    
    <%if current_user.reviews.any?%>
      <ul>
        <% current_user.reviews[0..5].each do |review| %>
        <li>
          <% if Movie.find(review.movie_id).thumbnail_poster_link %>
            <%= image_tag(Movie.find(review.movie_id).thumbnail_poster_link, size: '21x31') %>
          <% end %>
          <%= link_to Movie.find(review.movie_id).title, 
          movie_path(:movie_id => Movie.find(review.movie_id).rotten_tomatoes_id, id: 'show') %>
        </li>
        <% end %>
      </ul>
  <%else%>
    <h4> You haven't reviewed any movies yet! Search for your favourite movie and tell us what you think! </h4>
  <%end%>
   </div>
  </div>
<%else%>
  <h2> Welcome to MovieUp! </h2>
  <h3> <%=link_to 'Sign Up', new_user_registration_path%> to begin your moviest journey! </h3>
  <h4> Or, if you're tired of filling in your details, you can always 
    <%=link_to 'Sign Up with Facebook', user_omniauth_authorize_path(:facebook)%>.</h4>
<%end%>

app/views/welcome/temp.html.erb
  <!DOCTYPE html> 
    <html lang="en"> 
      <head> 
        <meta charset="utf-8"> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta name="description" content=""> <meta name="author" content=""> 
        <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

  <title>Movienator - Register</title>
  <!-- Bootstrap core CSS --> <link href="css/bootstrap.min.css" rel="stylesheet"> <!-- Bootstrap theme --> <link href="css/bootstrap-theme.min.css" rel="stylesheet"> </head> 
  <body>

  <nav class="navbar navbar-default" role="navigation"> 
      <div class="container-fluid"> <!-- Brand and toggle get grouped for better mobile display --> 
        <div class="navbar-header"> 
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
          <span class="sr-only">Toggle navigation</span> 
          <span class="icon-bar"></span> <span class="icon-bar"></span> 
          <span class="icon-bar"></span> </button> <a class="navbar-brand" href="#">Brand</a> 
        </div>

  <!-- Collect the nav links, forms, and other content for toggling --> 
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
    <ul class="nav navbar-nav"> 
      <li class="active"><a href="#">Link</a></li> 
      <li><a href="#">Link</a></li> 
      <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a> <ul class="dropdown-menu"> <li><a href="#">Action</a></li> <li><a href="#">Another action</a></li> <li><a href="#">Something else here</a></li> <li class="divider"></li> <li><a href="#">Separated link</a></li> <li class="divider"></li> <li><a href="#">One more separated link</a></li> </ul> </li> </ul> <form class="navbar-form navbar-left" role="search"> <div class="form-group"> <input type="text" class="form-control" placeholder="Search"> </div> <button type="submit" class="btn btn-default">Submit</button> </form> <ul class="nav navbar-nav navbar-right"> <li><a href="#">Link</a></li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a> <ul class="dropdown-menu"> <li><a href="#">Action</a></li> <li><a href="#">Another action</a></li> <li><a href="#">Something else here</a></li> <li class="divider"></li> <li><a href="#">Separated link</a></li> </ul> </li> </ul> </div><!-- /.navbar-collapse --> </div><!-- /.container-fluid --> </nav> </body> </html>